mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', include("webapp.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("webapp.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

webapp/urls.py
from django.urls import path
from .views import SignUpView
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("coment/new", views.comm_new, name="comm_new"),
    path("kabinet/<int:pk>/", views.kab_detail, name="kab_detail")
]

webapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Users(AbstractUser):
    pass
    YEAR_IN_SCHOOL_CHOICES = [
        ('7', '7 класс'),
        ('8', '8 класс'),
        ('9', '9 класс'),
        ('10', '10 класс'),
        ('11', '11 класс'),
    ]
    grade = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default='7',
    )

    def __str__(self):
        return self.username


class Kabinet(models.Model):
    SUBJECT = [
        ('math', 'Математика'),
        ('phys', 'Физика'),
        ('russ', 'Русский язык'),
        ('it', 'Информатика'),
    ]
    subject = models.CharField(
        max_length=4,
        choices=SUBJECT,
        default='math',
    )
    number = models.IntegerField()
    ave_rating = models.FloatField()

    def __str__(self):
        return str(self.number)



class Ratings(models.Model):
    rating = models.IntegerField()
    user = models.ForeignKey('Users', on_delete=models.CASCADE)
    kabinet = models.ForeignKey('Kabinet', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.kabinet) + "_" + str(self.rating)


class Comments(models.Model):
    coment = models.TextField()
    user = models.ForeignKey('Users', on_delete=models.CASCADE)
    kabinet = models.ForeignKey('Kabinet', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.kabinet) + "_" + str(self.coment[0:10])

# Create your models here.

webapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from . import models


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = models.Users
        fields = ("username", "email")

class Comm(forms.ModelForm):

    class Meta:
        model = models.Comments
        fields = ("coment", "kabinet")

webapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.shortcuts import redirect

from .forms import CustomUserCreationForm
from . import forms
from . import models

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"
# Create your views here.


def comm_new(request):
    if request.method == "POST":
        form = forms.Comm(request.POST)
        post = form.save(commit = False)
        post.user = request.user
        if models.Comments.objects.filter(user = request.user, kabinet = post.kabinet).exists() == 0:
            post.save()
        return redirect('home')
    else:
        form = forms.Comm()
    return render(request, 'new_comm.html', {'form': form})


def home(request):
    kab = models.Kabinet.objects.all()
    return render(request, 'home.html', {'kab': kab})

def kab_detail(request, pk):
    kab = models.Kabinet.objects.get(pk=pk)
    coments = models.Comments.objects.filter(kabinet=kab)
    return render(request, 'kabinet_detail.html', {'kab': kab,'coments':coments})

webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link href="{% static 'css/webapp.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Rubik+80s+Fade">
</head>
<body>
  <div class="header">
    <a href="/" class="logo">1502 Внутришкольный сайт</a>
    <div class="header-right">
    {% if user.is_authenticated %}
        <a href="{% url 'comm_new' %}">Добавить отзыв</a>
        <a class="active" href="{% url 'logout' %}">Log Out</a>
{% else %}
        <a class="active" href="{% url 'login' %}">Log In</a>
        <a class="active" href="{% url 'signup' %}">Sign Up</a>
{% endif %}
      </div>
  </div>

  <main>
    {% block content %}
    {% endblock %}
  </main>

<div class="footer">
    <a href="https://vk.com/kirka310"> Обратная связь </a>
</div>
</body>

</html>

webapp/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}

{% for i in kab %}
<div class="kablist">
    {% if i.subject == 'math' %}
        <img src="{% static 'image/kab_math.jpg' %}" alt="Math" width="900" height="900">
    {% elif i.subject == 'russ' %}
        <img src="{% static 'image/kab_rus.jpg' %}" alt="Rus" width="900" height="900">
    {% elif i.subject == 'phys' %}
        <img src="{% static 'image/kab_phys.jpg' %}" alt="Phys" width="900" height="900">
    {% elif i.subject == 'it' %}
        <img src="{% static 'image/kab_it.jpg' %}" alt="IT" width="900" height="900">
    {% else %}
        <img src="{% static 'image/kab_null.jpg' %}" alt="Null" width="900" height="900">
    {% endif %}
    <div class="kab">
        <h3><a href='{% url 'kab_detail' pk=i.pk %}'>Кабинет {{ i.number }}</a></h3>
        <p>{{ i.get_subject_display }}</p>
    </div>
</div>
{% endfor %}
{% endblock %}

webapp/templates/kabinet_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="cab_detail">
    <div>
        {% if kab.subject == 'math' %}
        <img class="cabdetailimage" src="{% static 'image/kab_math.jpg' %}" alt="Math" width="900" height="900">
    {% elif kab.subject == 'russ' %}
        <img class="cabdetailimage" src="{% static 'image/kab_rus.jpg' %}" alt="Rus" width="900" height="900">
    {% elif kab.subject == 'phys' %}
        <img class="cabdetailimage" src="{% static 'image/kab_phys.jpg' %}" alt="Phys" width="900" height="900">
    {% elif kab.subject == 'it' %}
        <img class="cabdetailimage" src="{% static 'image/kab_it.jpg' %}" alt="IT" width="900" height="900">
    {% else %}
        <img class="cabdetailimage" src="{% static 'image/kab_null.jpg' %}" alt="Null" width="900" height="900">
    {% endif %}
    </div>
    <div class="cabdetailtext">
        <h3>Кабинет {{ kab.number }}</h3>
        <p><b>Предмет: </b> {{ kab.get_subject_display }}<br><b>Рейтинг: </b> {{ kab.ave_rating }}</p>
    </div>
</div>

<div class="comment_list">
    <h3>Комментарии:</h3>
    {% for i in coments %}
        <div class = "comment">
            <div class="comm_author">{{ i.user }}</div>
            <div class="comm_text">{{ i.coment }}</div>
        </div>
    {% endfor %}

</div>


{% endblock %}

webapp/templates/new_comm.html
{% extends 'base.html' %}

{% block content %}
<div class="new_comm">
     <h2>Добавьте новый отзыв к кабинету</h2>
    <form method = "POST" class = "Comm">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = "submit"> Save </button>
    </form>
</div>

{% endblock %}